apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - my-db-persistentvolumeclaim.yaml
  - db-deployment.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - db-service.yaml
  - backend-service.yaml
  - frontend-service.yaml

  